# Generated by Django 6.0.6 on 2026-06-28 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
        ('users', '0003_alter_cita_estado_alter_disponibilidad_barbero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
