# Generated by Django 6.0.6 on 2026-08-08 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisFacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_original', models.ImageField(upload_to='analisis_ia/originales/')),
                ('forma_rostro', models.CharField(blank=True, choices=[('ovalado', 'Ovalado'), ('redondo', 'Redondo'), ('cuadrado', 'Cuadrado'), ('corazon', 'Corazón'), ('alargado', 'Alargado / Oblongo'), ('diamante', 'Diamante'), ('triangular', 'Triangular')], max_length=20)),
                ('indice_cefalico', models.CharField(blank=True, choices=[('dolicocefalo', 'Dolicocéfalo (cabeza alargada)'), ('mesocefalo', 'Mesocéfalo (cabeza proporcionada)'), ('braquicefalo', 'Braquicéfalo (cabeza ancha)')], max_length=20)),
                ('medidas', models.JSONField(blank=True, null=True)),
                ('tipo_cabello', models.CharField(blank=True, choices=[('1a', '1A - Liso fino'), ('1b', '1B - Liso medio'), ('1c', '1C - Liso grueso'), ('2a', '2A - Ondulado suave'), ('2b', '2B - Ondulado medio'), ('2c', '2C - Ondulado definido'), ('3a', '3A - Rizado suelto'), ('3b', '3B - Rizado medio'), ('3c', '3C - Rizado apretado'), ('4a', '4A - Afro suave'), ('4b', '4B - Afro definido'), ('4c', '4C - Afro muy apretado')], max_length=5)),
                ('descripcion_ia', models.TextField(blank=True)),
                ('nombre_corte_sugerido', models.CharField(blank=True, max_length=100)),
                ('imagen_resultado', models.ImageField(blank=True, null=True, upload_to='analisis_ia/resultados/')),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('error_detalle', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('corte_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_ia', to='servicios.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_faciales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
