# Generated by Django 6.0.6 on 2026-08-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_ia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisfacial',
            name='imagen_resultado_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='analisis_ia/resultados/'),
        ),
    ]
