# Generated by Django 6.0.6 on 2026-09-17 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_ia', '0004_codigoseguridadia_barbero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoseguridadia',
            name='barbero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_ia_recibidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
